plugins = []
headers = []
redirects = []

[settings]
password = ""

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\rodri\\.openclaw\\workspace\\hku-date\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]